[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0,0,0,1

[Metadata]
Name=Arthemist Mini Cyber Terminal
Author=ChatGPT
Information=Minimal Cyberpunk Hacker Profile
Version=2.0

[Variables]
FontName=Consolas
TextColor=0,230,130,255
TitleColor=0,255,180,255
SubColor=0,150,90,255
BackColor=20,25,30,90


;========================
; GLASS BLUR STYLE
;========================

[Background]
Meter=Shape
Shape=Rectangle 0,0,360,280,16 | Fill Color 20,25,30,90 | StrokeWidth 1 | Stroke Color 255,255,255,50


[GlassHighlight]
Meter=Shape
Shape=Rectangle 5,5,350,270,14 | Fill Color 255,255,255,18 | StrokeWidth 0


[GlassTint]
Meter=Shape
Shape=Rectangle 10,10,340,260,12 | Fill Color 0,255,180,10 | StrokeWidth 0




;========================
; MEASURES
;========================

[MeasureTime]
Measure=Time
Format=%H:%M:%S

[MeasureDate]
Measure=Time
Format=%d/%m/%Y

[MeasureCPU]
Measure=CPU

[MeasureRAM]
Measure=PhysicalMemory


;========================
; BACKGROUND
;========================

[Background]
Meter=Shape
Shape=Rectangle 0,0,360,280,12 | Fill Color #BackColor# | StrokeWidth 1 | Stroke Color 0,255,120,100


;========================
; HEADER
;========================

[Title]
Meter=String
Text=Arthemist OS
X=18
Y=12
FontFace=#FontName#
FontSize=14
FontColor=#TitleColor#
StringStyle=Bold
AntiAlias=1


[Subtitle]
Meter=String
Text=CYBER TERMINAL v2.0
X=20
Y=35
FontFace=#FontName#
FontSize=8
FontColor=#SubColor#
AntiAlias=1


[Line]
Meter=Shape
Shape=Line 18,55,340,55 | StrokeWidth 1 | Stroke Color 0,255,120,100


;========================
; PROFILE
;========================

[Profile]
Meter=String
X=18
Y=68
FontFace=#FontName#
FontSize=9
FontColor=#TextColor#
AntiAlias=1
Text=> USER: Arthemist#CRLF#> AGE : 17#CRLF#> CLASS: XII TKJ 1#CRLF#> STATUS: ONLINE#CRLF#> LEVEL: ROOT#CRLF#> FIREWALL: ACTIVE


;========================
; CLOCK
;========================

[Clock]
Meter=String
MeasureName=MeasureTime
X=18
Y=175
FontFace=#FontName#
FontSize=26
FontColor=#TitleColor#
StringStyle=Bold
AntiAlias=1


[Date]
Meter=String
MeasureName=MeasureDate
X=20
Y=210
FontFace=#FontName#
FontSize=8
FontColor=#SubColor#
AntiAlias=1


;========================
; SYSTEM MONITOR
;========================

[CPU]
Meter=String
MeasureName=MeasureCPU
Text=CPU %1%%
X=220
Y=175
FontFace=#FontName#
FontSize=9
FontColor=#TextColor#
AntiAlias=1


[CPUBar]
Meter=Bar
MeasureName=MeasureCPU
X=220
Y=195
W=110
H=5
BarColor=0,255,120,255
SolidColor=25,25,25,255


[RAM]
Meter=String
MeasureName=MeasureRAM
Text=RAM %1%%
X=220
Y=215
FontFace=#FontName#
FontSize=9
FontColor=#TextColor#
AntiAlias=1


[RAMBar]
Meter=Bar
MeasureName=MeasureRAM
X=220
Y=235
W=110
H=5
BarColor=0,255,120,255
SolidColor=25,25,25,255


;========================
; FOOTER
;========================

[Footer]
Meter=String
Text=>>> SYSTEM READY <<<
X=18
Y=255
FontFace=#FontName#
FontSize=8
FontColor=#SubColor#
AntiAlias=1
